export const REVOLUTION_CAUSES = Object.freeze([
  {
    id: "tax-resistance",
    fromEventId: "stamp-act",
    toEventId: "massacre",
    label: "Resistance hardened",
    detail: "The Stamp Act crisis helped colonists build protest networks and sharpened distrust of Parliament and the troops later stationed in Boston.",
  },
  {
    id: "public-memory",
    fromEventId: "massacre",
    toEventId: "tea-party",
    label: "Memory became mobilization",
    detail: "Patriot leaders kept the Boston Massacre in public memory, making later resistance to parliamentary taxation easier to organize across the town.",
  },
  {
    id: "punishment-unity",
    fromEventId: "tea-party",
    toEventId: "congress",
    label: "Punishment produced unity",
    detail: "Britain answered the Tea Party with coercive measures against Massachusetts. Other colonies responded by coordinating at the First Continental Congress.",
  },
]);

export const REVOLUTION_PEOPLE = Object.freeze([
  {
    id: "samuel-adams",
    name: "Samuel Adams",
    lifespan: "1722-1803",
    role: "Organizer and Massachusetts legislator",
    side: "Patriot",
    status: "Archive subject acquired",
    summary: "A political organizer who helped turn resistance to parliamentary taxation into coordinated action across Massachusetts and the colonies.",
    goal: "Protect colonial self-government and build a common resistance movement.",
    tension: "He used public meetings, print, and committees to mobilize opposition while avoiding the appearance of uncontrolled disorder.",
    eventIds: ["stamp-act", "massacre", "tea-party", "congress"],
    evidenceIds: ["gazette-report", "tea-act"],
    relation: "Opposed Governor Hutchinson’s enforcement of imperial policy and worked alongside merchant leaders such as John Hancock.",
  },
  {
    id: "thomas-hutchinson",
    name: "Thomas Hutchinson",
    lifespan: "1711-1780",
    role: "Royal governor of Massachusetts",
    side: "Crown",
    status: "Perspective available",
    summary: "A Massachusetts-born official who defended imperial authority during an increasingly volatile period of colonial protest.",
    goal: "Preserve lawful government and enforce the Crown’s instructions in Massachusetts.",
    tension: "He understood local politics intimately, yet his refusal to let the tea ships depart made him a central target of Patriot anger.",
    eventIds: ["massacre", "tea-party"],
    evidenceIds: ["dartmouth-record", "tea-act"],
    relation: "Samuel Adams treated Hutchinson as the face of imperial overreach; Hutchinson viewed the Patriot movement as a threat to lawful order.",
  },
  {
    id: "george-hewes",
    name: "George Robert Twelves Hewes",
    lifespan: "1742-1840",
    role: "Shoemaker, participant, and later eyewitness",
    side: "Witness",
    status: "Eyewitness account indexed",
    summary: "A Boston artisan whose later recollections became one of the best-known personal accounts of the Tea Party.",
    goal: "Resist policies he believed reduced ordinary colonists to political dependence.",
    tension: "His memories preserve vivid details, but they were recorded decades afterward and must be compared with contemporary reports.",
    eventIds: ["massacre", "tea-party"],
    evidenceIds: ["hatchet", "tea-chest", "gazette-report"],
    relation: "Hewes represents the artisans and working people whose actions gave physical force to arguments advanced by Patriot leaders.",
  },
  {
    id: "john-hancock",
    name: "John Hancock",
    lifespan: "1737-1793",
    role: "Merchant and Patriot political leader",
    side: "Patriot",
    status: "Merchant network indexed",
    summary: "A wealthy Boston merchant whose public standing, commercial interests, and political leadership connected elite opposition with street-level protest.",
    goal: "Defend colonial rights and strengthen intercolonial political cooperation.",
    tension: "His wealth and status gave the movement influence, while customs disputes made his own commercial position politically charged.",
    eventIds: ["massacre", "tea-party", "congress"],
    evidenceIds: ["tea-act", "dartmouth-record"],
    relation: "A close political ally of Samuel Adams who helped connect Boston resistance to broader colonial leadership.",
  },
]);

export const REVOLUTION_EVIDENCE = Object.freeze([
  {
    id: "tea-chest",
    title: "East India Company Tea Chest",
    type: "object",
    date: "1773",
    sourceType: "Material reconstruction",
    clueId: "tea-chest",
    eventId: "tea-party",
    personIds: ["george-hewes"],
    summary: "A reconstruction of the cargo deliberately destroyed aboard the tea ships.",
    shows: "The protesters targeted the taxed commodity and made the political dispute physically visible.",
    limitation: "This model represents a category of cargo; it is not claimed to be one of the surviving original chests.",
    claim: "The Tea Party was focused on the tea cargo rather than indiscriminate destruction.",
  },
  {
    id: "hatchet",
    title: "Ship Carpenter’s Hatchet",
    type: "object",
    date: "December 16, 1773",
    sourceType: "Tool interpreted through testimony",
    clueId: "hatchet",
    eventId: "tea-party",
    personIds: ["george-hewes"],
    summary: "A period tool of the kind witnesses associated with breaking open the tea chests.",
    shows: "The destruction was rapid, deliberate, and directed at making the tea impossible to recover for sale.",
    limitation: "A representative tool cannot identify its owner or prove which participant used it.",
    claim: "Participants used ordinary tools to carry out a carefully bounded act of destruction.",
  },
  {
    id: "lantern",
    title: "Hooded Wharf Lantern",
    type: "object",
    date: "December 16, 1773",
    sourceType: "Material reconstruction",
    clueId: "lantern",
    eventId: "tea-party",
    personIds: ["george-hewes"],
    summary: "Portable light suitable for moving and working along a dark waterfront.",
    shows: "The action took place after sunset and required enough organization to work across several ships in limited light.",
    limitation: "The lantern illustrates working conditions but cannot establish the identities of participants.",
    claim: "The Tea Party was an organized night operation rather than a spontaneous daytime riot.",
  },
  {
    id: "dartmouth-record",
    title: "Dartmouth Arrival Record",
    type: "document",
    date: "November 28, 1773",
    sourceType: "Shipping and customs record",
    clueId: "ship",
    eventId: "tea-party",
    personIds: ["thomas-hutchinson", "john-hancock"],
    summary: "The Dartmouth arrived carrying East India Company tea and faced a customs deadline while Bostonians demanded that the cargo be returned.",
    shows: "The ship’s legal deadline turned a political argument into an urgent confrontation.",
    limitation: "An administrative record documents cargo and timing, not the motives of the crowd.",
    claim: "Imperial customs rules constrained the choices available to the ship and the town meeting.",
  },
  {
    id: "gazette-report",
    title: "Boston Gazette Report",
    type: "newspaper",
    date: "December 20, 1773",
    sourceType: "Contemporary newspaper account",
    eventId: "tea-party",
    personIds: ["samuel-adams", "george-hewes"],
    summary: "A near-contemporary public account emphasizing the destruction of tea and the restraint shown toward ships and other property.",
    shows: "Patriot reporting framed the action as disciplined political resistance rather than looting.",
    limitation: "The Gazette supported the Patriot cause, so its framing must be read alongside records from officials and merchants.",
    claim: "Contemporary Patriot accounts deliberately presented the protest as selective and orderly.",
  },
  {
    id: "tea-act",
    title: "Tea Act",
    type: "law",
    date: "May 10, 1773",
    sourceType: "Act of Parliament",
    eventId: "tea-party",
    personIds: ["samuel-adams", "thomas-hutchinson", "john-hancock"],
    summary: "Legislation designed to help the East India Company sell tea in the colonies while retaining Parliament’s tea duty.",
    shows: "The dispute concerned political authority and commercial privilege as well as the price of tea.",
    limitation: "The law states Parliament’s policy; it does not by itself reveal how every colonist understood or experienced it.",
    claim: "Colonial resistance centered on Parliament’s claimed right to tax and regulate trade without colonial consent.",
  },
]);

export const MEMORY_QUESTIONS = Object.freeze([
  {
    id: "chronology",
    dimension: "Chronology",
    prompt: "Which event occurred first?",
    options: [
      { id: "tea-party", label: "Boston Tea Party" },
      { id: "stamp-act", label: "Stamp Act" },
      { id: "massacre", label: "Boston Massacre" },
    ],
    answerId: "stamp-act",
    explanation: "Parliament passed the Stamp Act in 1765, five years before the Boston Massacre and eight years before the Tea Party.",
    reviewSection: "timeline",
  },
  {
    id: "perspective",
    dimension: "People & Perspectives",
    prompt: "Who represented the Crown’s authority in Massachusetts during the Tea Party crisis?",
    options: [
      { id: "samuel-adams", label: "Samuel Adams" },
      { id: "thomas-hutchinson", label: "Thomas Hutchinson" },
      { id: "george-hewes", label: "George R. T. Hewes" },
    ],
    answerId: "thomas-hutchinson",
    explanation: "Royal governor Thomas Hutchinson defended imperial authority and refused to let the tea ships leave without completing the required customs process.",
    reviewSection: "people",
  },
  {
    id: "evidence",
    dimension: "Evidence Reasoning",
    prompt: "Which source best supports the claim that the protesters avoided general looting?",
    options: [
      { id: "tea-act", label: "The text of the Tea Act" },
      { id: "gazette-report", label: "A contemporary Boston Gazette report" },
      { id: "dartmouth-record", label: "The Dartmouth arrival record" },
    ],
    answerId: "gazette-report",
    explanation: "The newspaper account directly describes what participants destroyed and emphasizes that ships and unrelated property were left unharmed.",
    reviewSection: "evidence",
  },
  {
    id: "causality",
    dimension: "Cause & Effect",
    prompt: "How did Britain’s response to the Tea Party encourage colonial unity?",
    options: [
      { id: "lowered-tax", label: "Parliament immediately removed every colonial tax" },
      { id: "closed-boston", label: "Punitive measures against Massachusetts prompted colonies to coordinate" },
      { id: "returned-tea", label: "The East India Company returned all tea to Britain" },
    ],
    answerId: "closed-boston",
    explanation: "Coercive measures against Massachusetts alarmed other colonies and helped drive the meeting of the First Continental Congress in 1774.",
    reviewSection: "timeline",
  },
  {
    id: "synthesis",
    dimension: "Historical Explanation",
    prompt: "Why was the Tea Party about more than the price of tea?",
    options: [
      { id: "taste", label: "Colonists preferred a different kind of tea" },
      { id: "authority", label: "It challenged Parliament’s authority to tax and privilege a company without colonial consent" },
      { id: "shortage", label: "Boston had no tea available for purchase" },
    ],
    answerId: "authority",
    explanation: "The Tea Act made tea cheaper for some buyers, but accepting it also appeared to accept Parliament’s contested power to tax the colonies.",
    reviewSection: "evidence",
  },
]);
